language: node_js
node_js:
  - '8'
  - '10'
env:
  global:
    - CI=true
cache: yarn
git:
  depth: 5
script:
  - yarn test --runInBand --no-cache
deploy:
  - provider: script
    script: echo Deploy Githubpages
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: echo deploy to npm
    skip_cleanup: true
    on:
      branch: master
      tags: true
